apiVersion: v1
kind: Service
metadata:
  name: appminio
spec:
  selector:
    io.kompose.service: minio_container
  ports:
  - protocol: "TCP"
    port: 9000
    targetPort: 9000
    nodePort: 31900
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio_container
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: minio_container
    spec:
      containers:
      - args:
        - server
        - /export
        env:
        - name: MINIO_ACCESS_KEY
          value: minioAccessKey
        - name: MINIO_SECRET_KEY
          value: minioSecretKey
        image: minio/minio
        name: minio_container
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}